-- The Nueva School — 2026–2027 custom prerequisite / corequisite text
--
-- Populates courses.custom_prereq and courses.custom_coreq with the verbatim
-- Prerequisites / Corequisites wording from the course catalog. Courses whose
-- catalog entry lists "None" get an empty string ('').
--
-- Source of the verbatim text: the requirement lines captured at the end of each
-- course's long_description in scripts/nueva-school.sql (extracted from the PDF).
-- Safe to re-run; matches rows by school + course title.

BEGIN;

UPDATE courses AS c
SET custom_prereq = v.custom_prereq,
    custom_coreq  = v.custom_coreq
FROM (
  VALUES
    ($c$Dance$c$, $c$$c$, $c$$c$),
    ($c$Fall Production$c$, $c$$c$, $c$$c$),
    ($c$Groove Workshop$c$, $c$None, but some musical experience is encouraged.$c$, $c$$c$),
    ($c$Hit Harmonics: Studio Recording from Idea to Record$c$, $c$$c$, $c$$c$),
    ($c$Intro to Music Production$c$, $c$$c$, $c$$c$),
    ($c$Jazz Ensemble$c$, $c$Student must play an instrument.$c$, $c$$c$),
    ($c$Musical Theater$c$, $c$$c$, $c$$c$),
    ($c$Sound Experience$c$, $c$$c$, $c$$c$),
    ($c$Steel Drum Band$c$, $c$$c$, $c$$c$),
    ($c$Intro to Art & Fabrication$c$, $c$$c$, $c$$c$),
    ($c$Intro to Clay Sculpture$c$, $c$$c$, $c$$c$),
    ($c$Intro to Drawing$c$, $c$$c$, $c$$c$),
    ($c$Intro to Film & Video$c$, $c$$c$, $c$$c$),
    ($c$Mixed Media$c$, $c$$c$, $c$$c$),
    ($c$Intro to Painting$c$, $c$$c$, $c$$c$),
    ($c$Intro to Photography$c$, $c$$c$, $c$$c$),
    ($c$Adv. Art & Fabrication$c$, $c$Intro to Art & Fabrication$c$, $c$$c$),
    ($c$Adv. Clay Sculpture$c$, $c$Intro to Clay Sculpture$c$, $c$$c$),
    ($c$Adv. Drawing$c$, $c$Intro to Drawing$c$, $c$$c$),
    ($c$Adv. Film & Video$c$, $c$Intro to Film & Video$c$, $c$$c$),
    ($c$Adv. Painting$c$, $c$Intro to Painting$c$, $c$$c$),
    ($c$Adv. Photography$c$, $c$Intro to Photography$c$, $c$$c$),
    ($c$Adv. Studio Art$c$, $c$Any 2 full visual art courses (Intro & Advanced).$c$, $c$$c$),
    ($c$Fine Arts Teaching Fellowship$c$, $c$1) Successful completion of the desired course; 2) Read the Teaching Fellow Program Overview for program details, expectations, and timeline.$c$, $c$$c$),
    ($c$Advanced Machine Learning$c$, $c$At least one non-intro computer science elective at Nueva Upper School.$c$, $c$$c$),
    ($c$Algorithms$c$, $c$Completion of Intro to Computer Programming or Intro to Data Analysis, or approval of instructor.$c$, $c$$c$),
    ($c$Computer Security$c$, $c$Completion of Intro to Computer Programming or Intro to Data Analysis, or approval of instructor.$c$, $c$$c$),
    ($c$Computer Vision$c$, $c$Completion of Intro to Computer Programming or Intro to Data Analysis, or approval of instructor.$c$, $c$$c$),
    ($c$Data Science$c$, $c$Completion of Intro to Computer Programming or Intro to Data Analysis, or approval of instructor.$c$, $c$$c$),
    ($c$Intro to Computer Programming$c$, $c$$c$, $c$$c$),
    ($c$Intro to Data Analysis$c$, $c$$c$, $c$$c$),
    ($c$Intro to Machine Learning$c$, $c$At least one non-intro computer science elective at Nueva Upper School.$c$, $c$$c$),
    ($c$Mobile App Development$c$, $c$Completion of Intro to Computer Programming or Intro to Data Analysis, or approval of instructor.$c$, $c$$c$),
    ($c$Programming with OOP$c$, $c$Completion of Intro to Computer Programming or Intro to Data Analysis, or approval of instructor.$c$, $c$$c$),
    ($c$Software Engineering$c$, $c$At least one non-intro computer science elective at Nueva Upper School and comfort reading and writing code in at least one programming language.$c$, $c$$c$),
    ($c$Video Game Programming$c$, $c$Completion of Intro to Computer Programming or Intro to Data Analysis, or approval of instructor.$c$, $c$$c$),
    ($c$Computer Science Teaching Fellowship$c$, $c$1) Successful completion of the desired course; 2) Read the Teaching Fellow Program Overview for program details, expectations, and timeline.$c$, $c$$c$),
    ($c$Business Analytics$c$, $c$$c$, $c$$c$),
    ($c$Economic Inequality$c$, $c$$c$, $c$$c$),
    ($c$Economic Thesis Seminar$c$, $c$Any economics class and History 10.$c$, $c$$c$),
    ($c$Environmental Economics$c$, $c$$c$, $c$$c$),
    ($c$Intro to Macroeconomics$c$, $c$$c$, $c$$c$),
    ($c$Intro to Microeconomics$c$, $c$$c$, $c$$c$),
    ($c$Models of Group Decisions$c$, $c$Intro to Microeconomics and Math 2.$c$, $c$$c$),
    ($c$Economics Teaching Fellowship$c$, $c$1) Successful completion of the desired course; 2) Read the Teaching Fellow Program Overview for program details, expectations, and timeline.$c$, $c$$c$),
    ($c$All About Wearables$c$, $c$$c$, $c$$c$),
    ($c$Applied Engineering: Biomedical$c$, $c$Physics.$c$, $c$$c$),
    ($c$Architecture of Unbreakable Homes$c$, $c$$c$, $c$$c$),
    ($c$The Art of Repair$c$, $c$$c$, $c$$c$),
    ($c$Building Toys$c$, $c$$c$, $c$$c$),
    ($c$Creature Comforts$c$, $c$$c$, $c$$c$),
    ($c$Design Create Innovate (DCI)$c$, $c$$c$, $c$$c$),
    ($c$Film and Stage Costume Making$c$, $c$$c$, $c$$c$),
    ($c$Film & Stage Prop Making$c$, $c$$c$, $c$$c$),
    ($c$How to Build Anything?$c$, $c$$c$, $c$$c$),
    ($c$Intro Fabrication: Metal$c$, $c$$c$, $c$$c$),
    ($c$Intro to Fabrication: Wood$c$, $c$$c$, $c$$c$),
    ($c$Intro to CAD$c$, $c$$c$, $c$$c$),
    ($c$Intro to Mechatronics$c$, $c$$c$, $c$$c$),
    ($c$Materials Engineering$c$, $c$Physics.$c$, $c$$c$),
    ($c$Mechanical Engineering$c$, $c$Physics.$c$, $c$$c$),
    ($c$Product Design$c$, $c$$c$, $c$$c$),
    ($c$Engineering, Fabrication & Design Teaching Fellowship$c$, $c$1) Successful completion of the desired course; 2) Read the Teaching Fellow Program Overview for program details, expectations, and timeline.$c$, $c$$c$),
    ($c$English 9$c$, $c$$c$, $c$$c$),
    ($c$English 10$c$, $c$English 9.$c$, $c$$c$),
    ($c$English 11$c$, $c$English 10.$c$, $c$$c$),
    ($c$Cinema Studies$c$, $c$$c$, $c$$c$),
    ($c$Creative Writing$c$, $c$$c$, $c$$c$),
    ($c$Irish Literature$c$, $c$$c$, $c$$c$),
    ($c$War and Conflict in Literature$c$, $c$English 9.$c$, $c$$c$),
    ($c$Monstrosity$c$, $c$English 9.$c$, $c$$c$),
    ($c$Memoir and Adaptation$c$, $c$English 9.$c$, $c$$c$),
    ($c$19th-Century Adaptations$c$, $c$English 9.$c$, $c$$c$),
    ($c$Shakespeare Ever After$c$, $c$English 9.$c$, $c$$c$),
    ($c$The Tie that Binds: Family Dynamics in Shakespeare$c$, $c$English 9.$c$, $c$$c$),
    ($c$Women in Literature$c$, $c$English 9.$c$, $c$$c$),
    ($c$English Teaching Fellowship$c$, $c$1) Successful completion of the desired course; 2) Read the Teaching Fellow Program Overview for program details, expectations, and timeline.$c$, $c$$c$),
    ($c$Asian America$c$, $c$$c$, $c$$c$),
    ($c$Capitalism & Apocalypse$c$, $c$History 10.$c$, $c$$c$),
    ($c$Existentialism$c$, $c$$c$, $c$$c$),
    ($c$History 9 - World to 1500$c$, $c$$c$, $c$$c$),
    ($c$History 10 - Modern World$c$, $c$History 9.$c$, $c$$c$),
    ($c$History 11 - US History$c$, $c$History 10.$c$, $c$$c$),
    ($c$Ideas in Political Economy$c$, $c$$c$, $c$$c$),
    ($c$International Relations$c$, $c$History 10.$c$, $c$$c$),
    ($c$Religion and Modernity$c$, $c$History 9.$c$, $c$$c$),
    ($c$Sociocultural Anthropology: Culture, Exchange, Technology Studies$c$, $c$History 9.$c$, $c$$c$),
    ($c$What Is Philosophy?$c$, $c$$c$, $c$$c$),
    ($c$Work Ethics: A History$c$, $c$$c$, $c$$c$),
    ($c$History Teaching Fellowship$c$, $c$1) Successful completion of the desired course; 2) Read the Teaching Fellow Program Overview for program details, expectations, and timeline.$c$, $c$$c$),
    ($c$Art History: A Survey$c$, $c$$c$, $c$$c$),
    ($c$Psychological Disorders: Body, Mind, and Culture$c$, $c$Psychology 101; seniors who have taken advanced biology, anthropology, or online/summer psychology classes may also enroll.$c$, $c$$c$),
    ($c$Comparative Literature: Art and War$c$, $c$$c$, $c$$c$),
    ($c$Environmental Humanities$c$, $c$$c$, $c$$c$),
    ($c$Design + Systems Thinking: Building a Music Festival [Not Running in 2026-27]$c$, $c$$c$, $c$$c$),
    ($c$Free Block$c$, $c$$c$, $c$$c$),
    ($c$Gender and Sexuality$c$, $c$$c$, $c$$c$),
    ($c$Independent Study$c$, $c$$c$, $c$$c$),
    ($c$Independent Study: Internship$c$, $c$$c$, $c$$c$),
    ($c$Intro to Psychology$c$, $c$$c$, $c$$c$),
    ($c$Intro to Speech and Debate$c$, $c$$c$, $c$$c$),
    ($c$Journalism$c$, $c$$c$, $c$$c$),
    ($c$Linguistics: Logic and Language$c$, $c$$c$, $c$$c$),
    ($c$Philosophy of Consciousness and Personhood$c$, $c$$c$, $c$$c$),
    ($c$Psychology and Memory$c$, $c$Intro to Psychology, or grade 12 students with permission of instructor.$c$, $c$$c$),
    ($c$Research in Psychology$c$, $c$Intro to Psychology.$c$, $c$$c$),
    ($c$Translation Studies$c$, $c$Chinese 2, Japanese 2, Spanish 2, or the equivalent.$c$, $c$$c$),
    ($c$Yearbook Media Production$c$, $c$$c$, $c$$c$),
    ($c$Interdisciplinary Teaching Fellowship$c$, $c$1) Successful completion of the desired course; 2) Read the Teaching Fellow Program Overview for program details, expectations, and timeline.$c$, $c$$c$),
    ($c$Chinese 1$c$, $c$$c$, $c$$c$),
    ($c$Chinese 2$c$, $c$Chinese 1 or equivalent.$c$, $c$$c$),
    ($c$Chinese 3$c$, $c$Chinese 2 or equivalent.$c$, $c$$c$),
    ($c$Chinese 4$c$, $c$Chinese 3 or equivalent.$c$, $c$$c$),
    ($c$Chinese 5: Current Events & Film$c$, $c$Chinese 4 or equivalent.$c$, $c$$c$),
    ($c$Chinese Literature & Advanced Research$c$, $c$Chinese 4 or equivalent.$c$, $c$$c$),
    ($c$Japanese 1$c$, $c$$c$, $c$$c$),
    ($c$Japanese 2$c$, $c$Japanese 1 or equivalent.$c$, $c$$c$),
    ($c$Japanese 3$c$, $c$Japanese 2 or equivalent.$c$, $c$$c$),
    ($c$Japanese 4$c$, $c$Japanese 3 or equivalent.$c$, $c$$c$),
    ($c$Adv. Topics in Japanese$c$, $c$Japanese 4 or equivalent.$c$, $c$$c$),
    ($c$Spanish 1$c$, $c$$c$, $c$$c$),
    ($c$Spanish 2$c$, $c$Spanish 1 or equivalent.$c$, $c$$c$),
    ($c$Spanish 3$c$, $c$Spanish 2 or equivalent.$c$, $c$$c$),
    ($c$Spanish 4$c$, $c$Spanish 3 or equivalent.$c$, $c$$c$),
    ($c$Spanish Communication$c$, $c$Spanish 4 or equivalent.$c$, $c$$c$),
    ($c$Advanced Topics in Spanish: Cultural Analysis and Lifestyles$c$, $c$Spanish 4 or equivalent.$c$, $c$$c$),
    ($c$Languages Teaching Fellowship$c$, $c$1) Successful completion of the desired course; 2) Read the Teaching Fellow Program Overview for program details, expectations, and timeline.$c$, $c$$c$),
    ($c$Abstract Algebra$c$, $c$$c$, $c$$c$),
    ($c$Advanced Probability$c$, $c$Calculus.$c$, $c$$c$),
    ($c$Algebra Techniques$c$, $c$$c$, $c$Math 1.$c$),
    ($c$Calculus$c$, $c$Math 3.$c$, $c$$c$),
    ($c$Complex Analysis$c$, $c$Calculus, and ideally one more elective such as Linear Algebra or Multivariable Calculus.$c$, $c$$c$),
    ($c$Computational Biology$c$, $c$Math 3.$c$, $c$$c$),
    ($c$Core Mathematics Intensive X$c$, $c$Math 1 and Math Department Approval.$c$, $c$Core Mathematics Intensive Y.$c$),
    ($c$Core Mathematics Intensive Y$c$, $c$Math 1 and Math Department Approval.$c$, $c$Core Mathematics Intensive X.$c$),
    ($c$Differential Equations$c$, $c$Calculus.$c$, $c$$c$),
    ($c$Geometries Beyond Euclid$c$, $c$Math 3.$c$, $c$$c$),
    ($c$Linear Algebra$c$, $c$Math 3.$c$, $c$$c$),
    ($c$Math 1$c$, $c$$c$, $c$$c$),
    ($c$Math 2$c$, $c$Math 1.$c$, $c$$c$),
    ($c$Math 3$c$, $c$Math 2.$c$, $c$$c$),
    ($c$Math and Philosophy for Human Flourishing$c$, $c$Math 1.$c$, $c$$c$),
    ($c$Mathematical Modeling$c$, $c$Calculus.$c$, $c$$c$),
    ($c$Multivariable Calculus$c$, $c$Calculus.$c$, $c$$c$),
    ($c$Number Theory$c$, $c$$c$, $c$$c$),
    ($c$Statistics$c$, $c$Math 2.$c$, $c$$c$),
    ($c$Math Teaching Fellowship$c$, $c$1) Successful completion of the desired course; 2) Read the Teaching Fellow Program Overview for program details, expectations, and timeline.$c$, $c$$c$),
    ($c$Advanced Mechanics$c$, $c$Physics and Calculus.$c$, $c$$c$),
    ($c$Anatomy and Physiology$c$, $c$Biology.$c$, $c$$c$),
    ($c$Biology$c$, $c$Chemistry.$c$, $c$$c$),
    ($c$Biology Research Teams 1$c$, $c$Chemistry and Completed Course Application.$c$, $c$$c$),
    ($c$Biology Research Teams 2$c$, $c$Biology Research Teams 1.$c$, $c$$c$),
    ($c$Bioorganic Chemistry$c$, $c$Chemistry.$c$, $c$Math 3.$c$),
    ($c$Chemical Engineering$c$, $c$Chemistry.$c$, $c$Math 3.$c$),
    ($c$Chemistry$c$, $c$$c$, $c$$c$),
    ($c$Chemistry Consulting$c$, $c$Chemistry and Math 2.$c$, $c$$c$),
    ($c$Drug Design$c$, $c$Chemical Engineering or Bioorganic Chemistry.$c$, $c$$c$),
    ($c$Environmental Earth Science$c$, $c$$c$, $c$$c$),
    ($c$Immunology$c$, $c$Biology.$c$, $c$$c$),
    ($c$Marine Environments$c$, $c$$c$, $c$$c$),
    ($c$Mechanisms of Cancer$c$, $c$Biology.$c$, $c$$c$),
    ($c$Modern Physics$c$, $c$Physics.$c$, $c$$c$),
    ($c$Optics & Astrophysics$c$, $c$Physics.$c$, $c$$c$),
    ($c$Physics$c$, $c$$c$, $c$Math 2 (or higher).$c$),
    ($c$Physics Research$c$, $c$Physics and Consent of Instructor.$c$, $c$$c$),
    ($c$Semiconductor Processes$c$, $c$Modern Physics (Fall Semester).$c$, $c$$c$),
    ($c$Sensory Neuroscience$c$, $c$Biology.$c$, $c$$c$),
    ($c$Science Teaching Fellowship$c$, $c$1) Successful completion of the desired course; 2) Read the Teaching Fellow Program Overview for program details, expectations, and timeline.$c$, $c$$c$),
    ($c$Social Emotional Learning 9$c$, $c$$c$, $c$$c$),
    ($c$Social Emotional Learning 10$c$, $c$Social Emotional Learning 9.$c$, $c$$c$),
    ($c$Social Emotional Learning 11$c$, $c$Social Emotional Learning 10.$c$, $c$$c$),
    ($c$Senior Block$c$, $c$$c$, $c$$c$),
    ($c$Social Emotional Learning 12: The Good Life$c$, $c$Social Emotional Learning 11.$c$, $c$$c$),
    ($c$SEL Teaching Fellowship$c$, $c$1) Successful completion of the desired course; 2) Read the Teaching Fellow Program Overview for program details, expectations, and timeline.$c$, $c$$c$)
) AS v(title, custom_prereq, custom_coreq)
WHERE c.title = v.title
  AND c.school_id = (SELECT id FROM schools WHERE name = $c$The Nueva School$c$);

COMMIT;
